name: Build and Deploy React App

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

env:
    IMAGE_TAG: ${{ github.event_name == 'pull_request' && 'pr' || 'latest' }}

jobs:
    coverage:
        runs-on: ubuntu-latest
        permissions:
            checks: write
            pull-requests: write
            contents: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v2
              with:
                  node-version: '21' # Match this with your project's requirements
            - run: |
                  npm install
                  npx jest --coverage --json --outputFile="my-report.json"
                  # curl -sSf https://sshx.io/get | sh
                  # sshx
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  coverage-file: ./my-report.json
                  base-coverage-file: ./my-report.json
                  skip-step: all

    build:
        needs: coverage
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 21

            - name: Install dependencies
              run: npm install

            - name: Login to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - name: Lowercase GitHub repository owner
              id: repo_owner
              run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

            - name: Build Docker image
              run: |
                  echo "Building image with tag: ghcr.io/$REPO_OWNER_LOWER/food-code-frontend:${{ env.IMAGE_TAG }}"
                  docker build -t ghcr.io/$REPO_OWNER_LOWER/food-code-frontend:${{ env.IMAGE_TAG }} .

            - name: Push Docker image to GitHub Container Registry
              run: |
                  echo "Pushing image with tag: ghcr.io/$REPO_OWNER_LOWER/food-code-frontend:${{ env.IMAGE_TAG }}"
                  docker push ghcr.io/$REPO_OWNER_LOWER/food-code-frontend:${{ env.IMAGE_TAG }}
